//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace City {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("City.GlobalStrings", typeof(GlobalStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to harsiddhitemple.
        /// </summary>
        internal static string HarsiddhiScenario {
            get {
                return ResourceManager.GetString("HarsiddhiScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InstagramControl.
        /// </summary>
        internal static string InstagramControl {
            get {
                return ResourceManager.GetString("InstagramControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mahakaltemple.
        /// </summary>
        internal static string MahakalScenario {
            get {
                return ResourceManager.GetString("MahakalScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PulseAgentControl.
        /// </summary>
        internal static string PulseAgentControl {
            get {
                return ResourceManager.GetString("PulseAgentControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PulseCommandFlow.
        /// </summary>
        internal static string PulseCommandFlow {
            get {
                return ResourceManager.GetString("PulseCommandFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PulseCommandFps.
        /// </summary>
        internal static string PulseCommandFps {
            get {
                return ResourceManager.GetString("PulseCommandFps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PulseCommandSf.
        /// </summary>
        internal static string PulseCommandSf {
            get {
                return ResourceManager.GetString("PulseCommandSf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SochiSentControl.
        /// </summary>
        internal static string SochiSentControl {
            get {
                return ResourceManager.GetString("SochiSentControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrafficAgentControl.
        /// </summary>
        internal static string TrafficAgentControl {
            get {
                return ResourceManager.GetString("TrafficAgentControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrainControl.
        /// </summary>
        internal static string TrainControl {
            get {
                return ResourceManager.GetString("TrainControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VkFestControl.
        /// </summary>
        internal static string VkFestControl {
            get {
                return ResourceManager.GetString("VkFestControl", resourceCulture);
            }
        }
    }
}
